<?php

use \Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * @file
 * Primary module hooks for PageNotFound module.
 */

/**
 * Implements hook_entity_view().
 */
function pagenotfound_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'vehicle') {
    $release_date = $entity->get('field_release_date')->value;
    $date = new DateTime($release_date);
    $year = $date->format('Y');
    if ($year === "2020") {
      $response = new RedirectResponse('/404');
      $response->send();
    }
  }
}
